name: stream_feed_flutter_core
description: Stream Feed official Flutter SDK Core. Build your own feed experience using Dart and Flutter.
version: 0.8.0
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.9.1
  rxdart: ^0.27.7
  stream_feed:
    path: ../stream_feed
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
